config/routes.rb
Rails.application.routes.draw do
  root 'ads#status'

  get 'refresh' => 'ads#refresh'
  resources :countries

  resources :ads

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :country
  
  def check(browser)
    browser.text_field(name: 'q').set body
    browser.send_keys :enter
    browser.link(id: 'pnnext').wait_until_present
    target_text = 'intellectsoft'
    result = (browser.div(id: 'tads').present? && browser.div(id: 'tads').text.include?(target_text)) || (browser.div(id: 'mbEnd').present? && browser.div(id: 'mbEnd').text.include?(target_text))
    seo = browser.div(id: 'res').text.include?(target_text)
    self.passed = result
    self.seo = seo
    save if changed?

  end
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :ads, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  def self.refresh
    begin
      unless ENV['HEADLESS'].nil?
        require 'headless'
        headless = Headless.new
        headless.start
        logger.fatal('headless started')
      end
      Country.all.each do |country|
        begin
          # if ENV['BROWSER'].nil? || ENV['BROWSER'] == 'firefox'
          profile = Selenium::WebDriver::Firefox::Profile.new
          profile.proxy = Selenium::WebDriver::Proxy.new socks: country.proxy
          b = Watir::Browser.new :ff, profile: profile
          logger.fatal('firefox started')
          # else
          #   switches = ["--proxy-server=\"socks5://#{country.proxy}\""]
          #   b = Watir::Browser.new :chrome, switches: switches
          # end
          b.goto 'google.com'
          logger.fatal('google visited')
          country.ads.each { |ad| ad.check(b) }
        # ensure
          b.close if b.present?
        end
      end
    ensure
      if ENV['HEADLESS']
        headless.destroy
      end
    end

  end
end

app/controllers/ads_controller.rb
require 'watir-webdriver'

class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_action :set_sorted_ads, only: [:status, :refresh]

  def refresh
    Country.refresh
    render :status
  end

  def status
  end

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ad
    @ad = Ad.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ad_params
    params.require(:ad).permit(:body)
  end

  def set_sorted_ads
    @ads = Ad.all.includes(:country).order('country_id', :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/ads/_form.html.haml
= form_for @ad, html: { class: "form form-horizontal ad" } do |f|
  .form-group
    = f.label :body, class: 'control-label'
    .controls
      = f.text_field :body, class: 'form-control', required: true
    = error_span(@ad[:body])
  .form-group
    = f.label :country_id, class: 'control-label'
    .controls
      = f.text_field :country_id, class: 'form-control', required: true
    = error_span(@ad[:country_id])
  .form-group
    = f.label :passed, class: 'control-label'
    .controls
      = f.text_field :passed, class: 'form-control', required: true
    = error_span(@ad[:passed])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), ads_path, :class => 'btn btn-default'

app/views/ads/_row.html.haml
.row
  .col-lg-8.main
    =ad.body
  .col-lg-3.main
    =ad.country.name
  -if ad.seo?
    .col-lg-1.main
      SEO

app/views/ads/edit.html.haml
- model_class = Ad
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/ads/index.html.haml
- model_class = Ad
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:country_id)
      %th= model_class.human_attribute_name(:passed)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @ads.each do |ad|
      %tr
        %td= link_to ad.id, ad_path(ad)
        %td= ad.body
        %td= ad.country_id
        %td= ad.passed
        %td=l ad.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_ad_path(ad), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), ad_path(ad), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_ad_path, :class => 'btn btn-primary'

app/views/ads/new.html.haml
- model_class = Ad
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/ads/show.html.haml
- model_class = Ad
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @ad.body
%p
  %strong= model_class.human_attribute_name(:country_id) + ':'
  %br
  = @ad.country_id
%p
  %strong= model_class.human_attribute_name(:passed) + ':'
  %br
  = @ad.passed


= link_to t('.back', :default => t("helpers.links.back")), ads_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_ad_path(@ad), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), ad_path(@ad), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/ads/status.html.haml
%style
  body{background-color: #333333; color: #aaaaaa;}
Last updated:
=Ad.all.order(updated_at: :asc).last.updated_at.to_formatted_s(:short)
-@ads.each do |ad|
  -if ad.passed? || ad.seo?
    .passed
      =render partial:'ads/row', locals: {ad: ad}
  -else
    .failed
      =render partial:'ads/row', locals: {ad: ad}

app/views/countries/_form.html.haml
= form_for @country, html: { class: "form form-horizontal country" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@country[:name])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), countries_path, :class => 'btn btn-default'

app/views/countries/edit.html.haml
- model_class = Country
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/countries/index.html.haml
- model_class = Country
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @countries.each do |country|
      %tr
        %td= link_to country.id, country_path(country)
        %td= country.name
        %td=l country.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_country_path(country), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), country_path(country), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_country_path, :class => 'btn btn-primary'

app/views/countries/new.html.haml
- model_class = Country
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/countries/show.html.haml
- model_class = Country
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @country.name


= link_to t('.back', :default => t("helpers.links.back")), countries_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_country_path(@country), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), country_path(@country), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!!
%html
%head
%title GoogleAds
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
= csrf_meta_tags
%body
  .container-fluid
    = yield
= javascript_include_tag 'application', 'data-turbolinks-track' => true